# Generated by Django 5.0.4 on 2024-04-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorderPay', '0002_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Bank',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Bank_account',
            new_name='bank_account',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Denomination',
            new_name='denomination',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Location',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='employee',
            name='userID',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
