# Generated by Django 5.0.4 on 2024-04-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorderPay', '0003_rename_bank_employee_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bank_account',
            new_name='account',
        ),
        migrations.AddField(
            model_name='employee',
            name='withdraw_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
