# Generated by Django 5.0.4 on 2024-04-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorderPay', '0003_remove_employee_denomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='denomination',
            field=models.CharField(choices=[('rupees', 'rupees'), ('dollar', 'dollar'), ('euro', 'euro')], default='rupees', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='withdraw_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='worked_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
