# Generated by Django 5.0.4 on 2024-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorderPay', '0006_rename_timer_contract_requests_timer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions_request',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transactions_request',
            old_name='Bank_account_employee',
            new_name='bank_account_employee',
        ),
        migrations.RenameField(
            model_name='transactions_request',
            old_name='Bank_account_employer',
            new_name='bank_account_employer',
        ),
        migrations.RenameField(
            model_name='transactions_request',
            old_name='Bank_employee',
            new_name='bank_employee',
        ),
        migrations.RenameField(
            model_name='transactions_request',
            old_name='Bank_employer',
            new_name='bank_employer',
        ),
        migrations.RenameField(
            model_name='transactions_request',
            old_name='Country_employee',
            new_name='country_employee',
        ),
        migrations.RenameField(
            model_name='transactions_request',
            old_name='Country_employer',
            new_name='country_employer',
        ),
        migrations.AddField(
            model_name='transactions_request',
            name='den_employee',
            field=models.CharField(choices=[('rupees', 'rupees'), ('dollar', 'dollar'), ('euro', 'euro')], default='rupees', max_length=50),
        ),
        migrations.AddField(
            model_name='transactions_request',
            name='den_employer',
            field=models.CharField(choices=[('rupees', 'rupees'), ('dollar', 'dollar'), ('euro', 'euro')], default='rupees', max_length=50),
        ),
    ]
