# Generated by Django 5.0.4 on 2024-04-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorderPay', '0007_rename_amount_transactions_request_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions_request',
            name='status',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
