# Generated by Django 5.0.4 on 2024-04-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorderPay', '0008_transactions_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions_request',
            name='username_ee',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactions_request',
            name='username_er',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
