# Generated by Django 5.0.4 on 2024-04-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorderPay', '0009_transactions_request_username_ee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advance_approvals',
            name='employeeID',
        ),
        migrations.RemoveField(
            model_name='advance_requests',
            name='employeeID',
        ),
        migrations.RemoveField(
            model_name='withdraw_approvals',
            name='employeeID',
        ),
        migrations.AddField(
            model_name='advance_approvals',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advance_requests',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdraw_approvals',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
