# Generated by Django 5.0.4 on 2024-04-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorderPay', '0010_remove_advance_approvals_employeeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advance_approvals',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='advance_approvals',
            old_name='Interval',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='advance_approvals',
            old_name='Timer',
            new_name='interval',
        ),
        migrations.RenameField(
            model_name='advance_approvals',
            old_name='username',
            new_name='username_ee',
        ),
        migrations.AddField(
            model_name='advance_approvals',
            name='timer',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='advance_approvals',
            name='username_er',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
