# Generated by Django 5.0.4 on 2024-04-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorderPay', '0011_rename_amount_advance_approvals_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance_approvals',
            name='status',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
